/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.man;

import gui.login.login.*;
import javax.swing.table.DefaultTableModel;
import cnDatabase.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author ngô
 */
public class PnDetailIssue extends javax.swing.JPanel {

    String receiptNo;
    manHome man;
    PnExport im;
    DefaultTableModel model;

    public PnDetailIssue() {
        initComponents();
        initModel();
        // this.receiptNo = "no111";

    }

    public PnDetailIssue(manHome man, String receiptNo, PnExport im) {
        initComponents();
        this.receiptNo = receiptNo;
        this.im = im;
        initModel();
        txtNumbrer.setText(String.valueOf(tbDetail.getRowCount()));

        this.man = man;
        //  this.receiptNo = "no111";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbDetail = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        tbnBack = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtNumbrer = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setMinimumSize(new java.awt.Dimension(809, 496));

        tbDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Name", "Category", "Qantity", "Price", "Unit", "Manufacturer", "detailID", "billNo", "comment"
            }
        ));
        jScrollPane1.setViewportView(tbDetail);

        tbnBack.setText("Back");
        tbnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnBackActionPerformed(evt);
            }
        });

        jLabel7.setText("Number of product :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(txtNumbrer, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addComponent(tbnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(226, 226, 226))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbnBack)
                    .addComponent(jLabel7)
                    .addComponent(txtNumbrer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Detail of receipts");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(jLabel8))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel8)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnBackActionPerformed

        man.trypane.removeAll();
        man.trypane.add(im);
        man.trypane.validate();
        man.trypane.updateUI();


    }//GEN-LAST:event_tbnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbDetail;
    private javax.swing.JButton tbnBack;
    private javax.swing.JTextField txtNumbrer;
    // End of variables declaration//GEN-END:variables

    private void initModel() {
        model = (DefaultTableModel) tbDetail.getModel();
        EdetailList del = new EdetailList();
        CategoryList catl = new CategoryList();

        // receiptNo = "no111";
        for (Edetail d : del.getList()) {
            if (receiptNo.equals(d.billNo.toString())) {
                Vector v = new Vector();
                Connection cn = Mylib.getCon();
                if (cn != null) {

                    try {
                        Statement st = cn.createStatement();
                        ResultSet rs = st.executeQuery("select * from tbProduct");

                        //xu ly ket qua
                        //duyet cac dong trong rs => blist
                        while (rs.next()) {
                            String ID = rs.getString(1);

                            if (d.productID.equals(ID)) {
                                String name = rs.getString(2);
                                int cat = rs.getInt(3);
                                String catName = "";
                                for (Category c : catl.getList()) {
                                    if (cat == c.catID) {
                                        catName = c.catName;
                                    }
                                }
                                int quan = rs.getInt(4);
                                int price = rs.getInt(5);
                                String unit = rs.getString(6);
                                String manu = rs.getString(8);

                                v.add(d.productID);
                                v.add(name);
                                v.add(catName);
                                v.add(quan);
                                v.add(price);
                                v.add(unit);
                                v.add(manu);
                                v.add(d.detailID);
                                v.add(d.billNo);
                                v.add(d.comment);

                            }

                        }
                        //dong connection
                        rs.close();
                        cn.close();

                    } catch (SQLException ex) {
                        ex.printStackTrace();
                    }
                }
                model.addRow(v);
            }
        }
    }
}
