/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.admin;

import cnDatabase.Category;
import cnDatabase.CategoryList;
import cnDatabase.User;
import cnDatabase.UserList;
import gui.management.*;
import gui.man.*;
import gui.login.login.*;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ngô
 */
public class PnUser extends javax.swing.JPanel {

    FrAdmin ad;

    /**
     * Creates new form PProduct
     */
    public PnUser() {
        initComponents();
    }

    public PnUser(FrAdmin ad) {
        this.ad = ad;
        initComponents();
        initModel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbUser = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));

        tbUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID", "User name", "Role ID", "Sex", "Day of birth", "Phone", "Address"
            }
        ));
        jScrollPane1.setViewportView(tbUser);

        jButton2.setText("Add new");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Modify");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("User Management");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(339, 339, 339)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ad.trypane.removeAll();
        ad.trypane.add(new PnUserAdd(ad));
        ad.trypane.validate();
        ad.trypane.updateUI();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int i = tbUser.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(null, "please, choose one row to delete!");
            return;
        } else {
            int test = JOptionPane.showConfirmDialog(null, "are you sure!");

            if (test == JOptionPane.YES_OPTION) {
                UserList catl = new UserList();
                if (catl.delete(tbUser.getValueAt(i, 0).toString().trim())) {
                    JOptionPane.showMessageDialog(null, "delete successful!");
                    model.setRowCount(0);
                    initModel();
                } else {
                    JOptionPane.showMessageDialog(null, "Error delete!");
                }
            }

        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int i = tbUser.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(null, "please, choose one row to modify!");
            return;
        }
        String userID = tbUser.getValueAt(i, 0).toString().trim();
        String fullName = tbUser.getValueAt(i, 1).toString().trim();
        String Password = "";
        UserList ul = new UserList();
        for (User o : ul.getList()) {
            if (userID.equals(o.userID.trim())) {
                Password = o.Password;
            }
        }

        String Sex = "";
        String DOB = tbUser.getValueAt(i, 4).toString().trim();
        String Phone = tbUser.getValueAt(i, 5).toString().trim();
        String Adress = tbUser.getValueAt(i, 6).toString().trim();
        int role = 0;

        User ur = new User(userID, fullName, Password, Sex, DOB, Phone, Adress, role);

        ad.trypane.removeAll();
        ad.trypane.add(new PnUserModify(ad, ur));
        ad.trypane.validate();
        ad.trypane.updateUI();
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbUser;
    // End of variables declaration//GEN-END:variables
 DefaultTableModel model;

    private void initModel() {
        model = (DefaultTableModel) tbUser.getModel();
        UserList catl = new UserList();
        for (User o : catl.getList()) {
            Vector v = new Vector();
            v.add(o.userID);
            v.add(o.fullName);
            v.add(o.RoleID);
            if (o.Sex.equals("0")) {
                v.add("Female");
            } else {
                v.add("Male");
            }
            v.add(o.DOB);
            v.add(o.Phone);
            v.add(o.Adress);
            model.addRow(v);

        }

    }
}
